#!/usr/bin/env node
// Writes src/environments/version.ts with the current git short-SHA so the
// frontend can tag Sentry events with a `release` that matches the upload.
// Without this, Sentry events have no release and stale issues stay
// `unresolved` forever even after their fix-revision ships — same problem
// that bit JAVA-3 on the backend until SentryReleaseConfig landed.

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

let sha;
try {
  sha = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim();
} catch {
  sha = 'dev';
}

const content = `// AUTO-GENERATED by scripts/write-version.mjs — do not edit by hand.\nexport const APP_VERSION = 'deal-finder-app@${sha}';\n`;
writeFileSync('src/environments/version.ts', content);
console.log(`Wrote APP_VERSION = deal-finder-app@${sha}`);
